### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by CraftedCat** [alperensert/python_capmonster#1]
response = cap_monster.joinTaskResult(taskId=taskId)
  File "C:\Users\gdvvl\PycharmProjects\bitmex_checker\venv\lib\site-packages\python_capmonster\NoCaptchaTaskProxyless.py", line 68, in joinTaskResult
    self.checkResponse(response=task_result)
  File "C:\Users\gdvvl\PycharmProjects\bitmex_checker\venv\lib\site-packages\python_capmonster\CapmonsterClient.py", line 25, in checkResponse
    if response.get("errorId") != 0:
AttributeError: 'int' object has no attribute 'get'

**Comment by CraftedCat** [comment]
maybe:

if response["errorId"] != 0:

**Comment by alperensert** [comment]
I don't think so. I think, it's raise AttributeError because while you are checking response with **joinTaskResult** it's catching an error and return 0. I will take a look in 1 hour. Thank you for creating issue report!

**Comment by alperensert** [comment]
@CraftedCat ,

Sometimes capmonster.cloud returning 0 bytes to us. So we need to check responses have content or not.
I edited the *make_request (parent class's function for handle with any requests).* It's only raise CapmonsterException right now. So, you need to just use try/except for catching CapmonsterException and retry your request. Like this:
```python
try: 
    taskId = capmonster.createTask(website_key="WEBSITE_KEY", website_url="URL")
except CapmonsterException:
    # do something, your task create action isn't success.
try:
    response = capmonster.joinTaskResult(taskId=taskId)
except CapmonsterException:
    # do something another, while you waiting for task result,
    # capmonster.cloud returned 0 to you.
```
I think this will solve your problem. I'll release a hotfix for pypi package too in 10 minutes after posting this.
**One last note for using:** Maybe you need to decrease *maximum_time* of *joinTaskResult* function. As you know, these g-recaptcha responses just valid for 2 minutes after created.

_Thank you for notice it and reporting._

**Comment by alperensert** [comment]
By the way, as I saw, one of user of my library solving 4k captcha less than 10 minutes. That's why capmonster returning 0, their servers are crashes so much right now. I noticed the developer team about this and waiting for a response.

**Comment by CraftedCat** [comment]
Cool, thank you!
